spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    application:
        name: app-api
    jackson:
        time-zone: Asia/Seoul
    profiles:
        group:
            "local": "core-local, messages"
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    main:
        allow-bean-definition-overriding: true
    messages:
        basename: i18n/message
        fallback-to-system-locale: true
        encoding: UTF-8
logging:
    config: classpath:logback-spring.xml
springdoc:
    default-produces-media-type: application/json
    swagger-ui:
        tags-sorter: alpha
        operations-sorter: method
        doc-expansion: none

---
server:
    port: 9090
    servlet:
        encoding:
            enabled: true
            charset: UTF-8
            force: true
spring:
    config:
        activate:
            on-profile: local
springdoc:
    api-docs:
        path: "/api-docs"
        version: "OPENAPI_3_0"
    swagger-ui:
        enabled: true
slack:
    exception:
        channel: "#"
