@file:Suppress("ConstPropertyName", "MemberVisibilityCanBePrivate")

object Versions {
    const val openfeign = "4.2.1"
    const val kotlin = "2.1.20"
    const val kotlin_ksp = "2.1.20-2.0.0"
    const val spring_boot = "3.4.4"
    const val spring_ai = "1.1.0"
    const val io_awspring_version = "3.3.0"
    const val aws_crt_version = "0.31.3"
    const val spring_cloud_aws_dep_version = "3.3.0"
    const val awssdk_version = "2.30.14"
    const val dependency_management = "1.1.7"
    const val spring_boot_cloud =  "2024.0.0" //  2022.0.4
    const val kotlin_stdlib = kotlin
    const val kotlin_logging = "7.0.4"
    const val logback_common = "2.0.6"
    const val logback_classic = "1.5.18"
    const val logstash_logback_encoder = "8.1"
    const val junit_jupiter = "5.11.4"
    const val kotest_version = "5.9.1"
    const val kotest_extensions_spring = "1.3.0"
    const val mock = "1.13.16"
    const val hypersistence_utils_62 = "3.9.1"
    const val openapi = "2.8.4"
    const val coroutine_version = "1.10.1"
    const val javers = "7.8.0"
    const val jackson = "2.18.2"
    const val slack = "1.45.3"
    const val openfeign_querydsl_version = "6.10.1"
    const val http_client_version = "5.4.2"
    const val firebase_admin = "9.4.3"
    const val fastexcel = "0.18.4"
    const val jsoup = "1.19.1"
    const val commons_io = "2.18.0"
    const val commons_text = "1.13.0"
    const val commons_imaging = "1.0.0-alpha5"
    const val netty_resolver = "4.2.0.Final"
    const val shedlock = "6.3.1"
    const val langchain4j = "1.0.0-beta1"
    const val langchain4j_b = "1.0.0-alpha1"

    const val spring_session = "3.4.2"
    const val reactor_kotlin = "1.2.3"
    const val kotlin_reflect = "1.9.22"
    const val kotlinx_coroutines = "1.8.0"
    const val thymeleaf_extras = "3.1.3.RELEASE"
    const val thymeleaf_layout = "3.4.0"
}

